version: 0.0
os: linux # Amazon Linux, RHEL, Ubuntu Server일 경우 "linux", Windows Server일 경우 "windows"
files:
  - source: / # 인스턴스에 복사할 S3 파일의 경로. / 로 설정하면S3_BUCKET_NAME/PROJECT_NAME/GITHUB_SHA.zip을 가져온다.
    destination: /home/ubuntu/backend # S3에서 가져온 파일을 저장할 위치.
    overwrite: yes # 덮어쓰기를 허용하는 옵션.
