export enum NotificationFilter {
  ALL = 'ALL',
  RESERVED = 'RESERVED',
  LIKED = 'LIKED',
  COUPON_OR_PASS = 'COUPON_OR_PASS',
  UNREAD = 'UNREAD',
}

export enum NotificationRecipientType {
  ALL_STUDENTS = 'ALL_STUDENTS',
  SPECIFIC_LECTURE_STUDENTS = 'SPECIFIC_LECTURE_STUDENTS',
  SPECIFIC_STUDENTS = 'SPECIFIC_STUDENTS',
}
