import { applyDecorators } from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiCreatedResponse,
  ApiOkResponse,
  ApiOperation,
} from '@nestjs/swagger';
import { SwaggerApiResponse } from '@src/common/swagger/swagger-response';

export function ApiReadManyLectureProgress() {
  return applyDecorators(
    ApiOperation({
      summary: '강사 내 클래스 진행도 조회',
    }),
    ApiBearerAuth(),
    ApiOkResponse(
      SwaggerApiResponse.success('진행중 클래스 진행도 조회 완료', {
        statusCode: 200,
        data: {
          lectureProgress: [
            {
              id: 66,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-12-02T07:06:59.976Z',
              updatedAt: '2023-12-02T07:06:59.976Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 6,
              },
              progress: 50,
              allSchedule: 6,
              completedSchedule: 3,
            },
            {
              id: 61,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-26T15:55:05.488Z',
              updatedAt: '2023-11-26T15:55:05.488Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 60,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-26T15:54:48.774Z',
              updatedAt: '2023-11-26T15:54:48.774Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 50,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:37.000Z',
              endDate: '2024-11-24T23:38:25.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T14:00:47.169Z',
              updatedAt: '2023-11-22T14:00:47.169Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 49,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:35.000Z',
              endDate: '2024-11-24T23:38:23.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T14:00:34.299Z',
              updatedAt: '2023-11-22T14:00:34.299Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 48,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:36.000Z',
              endDate: '2024-11-24T23:38:22.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T14:00:13.601Z',
              updatedAt: '2023-11-22T14:00:13.601Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 47,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:35.000Z',
              endDate: '2024-11-24T23:38:23.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T13:54:22.080Z',
              updatedAt: '2023-11-22T13:54:22.080Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 34,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:33.000Z',
              endDate: '2023-11-24T23:38:20.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T13:40:40.476Z',
              updatedAt: '2023-11-09T13:40:40.476Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 32,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:33.000Z',
              endDate: '2023-11-24T23:38:21.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T05:10:10.133Z',
              updatedAt: '2023-11-09T05:11:01.289Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 6,
              },
              progress: 100,
              allSchedule: 6,
              completedSchedule: 6,
            },
            {
              id: 31,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:32.000Z',
              endDate: '2023-11-24T23:38:20.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T05:07:29.141Z',
              updatedAt: '2023-11-09T05:10:52.349Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 0,
              },
              progress: null,
              allSchedule: 0,
              completedSchedule: 0,
            },
            {
              id: 30,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:34.000Z',
              endDate: '2024-11-24T23:38:22.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T04:30:28.152Z',
              updatedAt: '2023-11-09T04:30:28.152Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 2,
              },
              progress: 100,
              allSchedule: 2,
              completedSchedule: 2,
            },
            {
              id: 29,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:36.000Z',
              endDate: '2024-11-24T23:38:24.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T04:29:34.085Z',
              updatedAt: '2023-11-09T05:06:31.912Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 24,
              },
              progress: 100,
              allSchedule: 24,
              completedSchedule: 24,
            },
            {
              id: 28,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:34.000Z',
              endDate: '2023-11-24T23:38:21.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T03:53:02.353Z',
              updatedAt: '2023-11-09T04:05:12.426Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 25,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:31.000Z',
              endDate: '2023-11-24T23:38:18.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-06T15:42:52.461Z',
              updatedAt: '2023-11-06T15:42:52.461Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 24,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:31.000Z',
              endDate: '2023-11-24T23:38:17.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-06T15:42:45.705Z',
              updatedAt: '2023-11-06T15:42:45.705Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
            {
              id: 23,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-11-24T23:38:32.000Z',
              endDate: '2023-11-24T23:38:19.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-06T15:39:19.860Z',
              updatedAt: '2023-11-06T15:39:19.860Z',
              deletedAt: null,
              _count: {
                lectureSchedule: 3,
              },
              progress: 100,
              allSchedule: 3,
              completedSchedule: 3,
            },
          ],
        },
      }),
    ),
  );
}
