import { applyDecorators } from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiCreatedResponse,
  ApiOkResponse,
  ApiOperation,
} from '@nestjs/swagger';
import { SwaggerApiResponse } from '@src/common/swagger/swagger-response';

export function ApiReadManyReservationThatCanBeCreated() {
  return applyDecorators(
    ApiOperation({
      summary: '유저 작성 가능한 예약 내역 조회',
    }),
    ApiBearerAuth(),
    ApiOkResponse(
      SwaggerApiResponse.success('조회 성공', {
        statusCode: 200,
        data: {
          reservation: [
            {
              id: 68,
              userId: 56,
              paymentId: 46,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 28,
              userId: 56,
              paymentId: 13,
              lectureScheduleId: 74,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-03T11:00:00.000Z',
              },
            },
            {
              id: 29,
              userId: 56,
              paymentId: 14,
              lectureScheduleId: 74,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-03T11:00:00.000Z',
              },
            },
            {
              id: 30,
              userId: 56,
              paymentId: 15,
              lectureScheduleId: 75,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-05T11:00:00.000Z',
              },
            },
            {
              id: 31,
              userId: 56,
              paymentId: 16,
              lectureScheduleId: 75,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-05T11:00:00.000Z',
              },
            },
            {
              id: 32,
              userId: 56,
              paymentId: 17,
              lectureScheduleId: 77,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 9,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-07T11:00:00.000Z',
              },
            },
            {
              id: 33,
              userId: 56,
              paymentId: 18,
              lectureScheduleId: 72,
              representative: '은서',
              phoneNumber: '01000000000',
              participants: 3,
              requests: 'dsfsfd',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-03T03:00:00.000Z',
              },
            },
            {
              id: 34,
              userId: 56,
              paymentId: 19,
              lectureScheduleId: 74,
              representative: '은서',
              phoneNumber: '01011111111',
              participants: 2,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-03T11:00:00.000Z',
              },
            },
            {
              id: 35,
              userId: 56,
              paymentId: 20,
              lectureScheduleId: 72,
              representative: '은서',
              phoneNumber: '01011111111',
              participants: 5,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-03T03:00:00.000Z',
              },
            },
            {
              id: 36,
              userId: 56,
              paymentId: 21,
              lectureScheduleId: 72,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 4,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '가비쌤과 함께하는 왁킹 클래스22',
                },
                startDateTime: '2023-10-03T03:00:00.000Z',
              },
            },
            {
              id: 37,
              userId: 56,
              paymentId: 22,
              lectureScheduleId: 242,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T05:00:00.000Z',
              },
            },
            {
              id: 38,
              userId: 56,
              paymentId: 23,
              lectureScheduleId: 242,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T05:00:00.000Z',
              },
            },
            {
              id: 39,
              userId: 56,
              paymentId: 24,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
            {
              id: 40,
              userId: 56,
              paymentId: 25,
              lectureScheduleId: 240,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '요청사항항',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T03:00:00.000Z',
              },
            },
            {
              id: 41,
              userId: 56,
              paymentId: 26,
              lectureScheduleId: 240,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '요청사항항',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T03:00:00.000Z',
              },
            },
            {
              id: 42,
              userId: 56,
              paymentId: 27,
              lectureScheduleId: 240,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '요청사항항',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T03:00:00.000Z',
              },
            },
            {
              id: 43,
              userId: 56,
              paymentId: 28,
              lectureScheduleId: 242,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '취소할거에염',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T05:00:00.000Z',
              },
            },
            {
              id: 44,
              userId: 56,
              paymentId: 29,
              lectureScheduleId: 242,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '취소할거에염',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T05:00:00.000Z',
              },
            },
            {
              id: 45,
              userId: 56,
              paymentId: 30,
              lectureScheduleId: 242,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '취소할거에염',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T05:00:00.000Z',
              },
            },
            {
              id: 46,
              userId: 56,
              paymentId: 31,
              lectureScheduleId: 242,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T05:00:00.000Z',
              },
            },
            {
              id: 47,
              userId: 56,
              paymentId: 32,
              lectureScheduleId: 239,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T01:00:00.000Z',
              },
            },
            {
              id: 48,
              userId: 56,
              paymentId: 33,
              lectureScheduleId: 239,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T01:00:00.000Z',
              },
            },
            {
              id: 49,
              userId: 56,
              paymentId: 34,
              lectureScheduleId: 242,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T05:00:00.000Z',
              },
            },
            {
              id: 56,
              userId: 56,
              paymentId: 35,
              lectureScheduleId: 239,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '호엥',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T01:00:00.000Z',
              },
            },
            {
              id: 57,
              userId: 56,
              paymentId: 36,
              lectureScheduleId: 239,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: 'dafdsadfadf',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T01:00:00.000Z',
              },
            },
            {
              id: 58,
              userId: 56,
              paymentId: 37,
              lectureScheduleId: 239,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: 'dafdsadfadf',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T01:00:00.000Z',
              },
            },
            {
              id: 59,
              userId: 56,
              paymentId: 38,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 60,
              userId: 56,
              paymentId: 39,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 61,
              userId: 56,
              paymentId: 40,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: 'asdasd',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
            {
              id: 62,
              userId: 56,
              paymentId: 41,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 63,
              userId: 56,
              paymentId: 42,
              lectureScheduleId: 239,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T01:00:00.000Z',
              },
            },
            {
              id: 64,
              userId: 56,
              paymentId: 43,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 65,
              userId: 56,
              paymentId: 44,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
            {
              id: 66,
              userId: 56,
              paymentId: 45,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 67,
              userId: 56,
              paymentId: 45,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 2,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
            {
              id: 69,
              userId: 56,
              paymentId: 46,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
            {
              id: 70,
              userId: 56,
              paymentId: 47,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 71,
              userId: 56,
              paymentId: 47,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 0,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
            {
              id: 72,
              userId: 56,
              paymentId: 48,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 0,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 73,
              userId: 56,
              paymentId: 48,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012341234',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
            {
              id: 74,
              userId: 56,
              paymentId: 49,
              lectureScheduleId: 243,
              representative: '은서',
              phoneNumber: '01012345678',
              participants: 0,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T09:00:00.000Z',
              },
            },
            {
              id: 75,
              userId: 56,
              paymentId: 49,
              lectureScheduleId: 241,
              representative: '은서',
              phoneNumber: '01012345678',
              participants: 1,
              requests: '',
              isEnabled: false,
              lectureSchedule: {
                lecture: {
                  title: '결제 테스트',
                },
                startDateTime: '2023-12-25T13:00:00.000Z',
              },
            },
          ],
        },
      }),
    ),
  );
}
