import { applyDecorators } from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiCreatedResponse,
  ApiOperation,
} from '@nestjs/swagger';
import { SwaggerApiResponse } from '@src/common/swagger/swagger-response';

export function ApiReadManyLectureWithLecturer() {
  return applyDecorators(
    ApiOperation({
      summary: '강사 id로 강의 조회',
    }),
    ApiBearerAuth(),
    ApiCreatedResponse(
      SwaggerApiResponse.success('강의 조회 성공', {
        statusCode: 200,
        data: {
          lecture: [
            {
              id: 24,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-03T00:00:00.000Z',
              endDate: '2023-10-03T00:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-06T15:42:45.705Z',
              updatedAt: '2023-11-06T15:42:45.705Z',
              deletedAt: null,
            },
            {
              id: 25,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-03T00:00:00.000Z',
              endDate: '2023-10-03T00:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-06T15:42:52.461Z',
              updatedAt: '2023-11-06T15:42:52.461Z',
              deletedAt: null,
            },
            {
              id: 23,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-03T00:00:00.000Z',
              endDate: '2023-10-03T00:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-06T15:39:19.860Z',
              updatedAt: '2023-11-06T15:39:19.860Z',
              deletedAt: null,
            },
            {
              id: 31,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T05:07:29.141Z',
              updatedAt: '2023-11-09T05:10:52.349Z',
              deletedAt: null,
            },
            {
              id: 32,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T05:10:10.133Z',
              updatedAt: '2023-11-09T05:11:01.289Z',
              deletedAt: null,
            },
            {
              id: 34,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T13:40:40.476Z',
              updatedAt: '2023-11-09T13:40:40.476Z',
              deletedAt: null,
            },
            {
              id: 28,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T03:53:02.353Z',
              updatedAt: '2023-11-09T04:05:12.426Z',
              deletedAt: null,
            },
            {
              id: 30,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T04:30:28.152Z',
              updatedAt: '2023-11-09T04:30:28.152Z',
              deletedAt: null,
            },
            {
              id: 47,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T13:54:22.080Z',
              updatedAt: '2023-11-22T13:54:22.080Z',
              deletedAt: null,
            },
            {
              id: 48,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T14:00:13.601Z',
              updatedAt: '2023-11-22T14:00:13.601Z',
              deletedAt: null,
            },
            {
              id: 49,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T14:00:34.299Z',
              updatedAt: '2023-11-22T14:00:34.299Z',
              deletedAt: null,
            },
            {
              id: 29,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '잘 운영할 예정',
              curriculum: '1주차 휴강',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 5,
              reservationDeadline: 2,
              reservationComment: '신발가져오세요',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-09T04:29:34.085Z',
              updatedAt: '2023-11-09T05:06:31.912Z',
              deletedAt: null,
            },
            {
              id: 50,
              lecturerId: 3,
              lectureTypeId: 1,
              lectureMethodId: 1,
              isGroup: true,
              startDate: '2023-10-02T15:00:00.000Z',
              endDate: '2023-10-02T15:00:00.000Z',
              title: '가비쌤과 함께하는 왁킹 클래스',
              introduction: '안녕하세용',
              curriculum: '첫날에 모하징',
              duration: 2,
              difficultyLevel: '상',
              minCapacity: 1,
              maxCapacity: 12,
              reservationDeadline: 1,
              reservationComment: '누구나 가능한!',
              price: 40000,
              noShowDeposit: 30000,
              reviewCount: 0,
              stars: 0,
              isActive: true,
              locationDescription: '버스타고 한번에',
              createdAt: '2023-11-22T14:00:47.169Z',
              updatedAt: '2023-11-22T14:00:47.169Z',
              deletedAt: null,
            },
          ],
        },
      }),
    ),
  );
}
