import { applyDecorators } from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiCreatedResponse,
  ApiOkResponse,
  ApiOperation,
} from '@nestjs/swagger';
import { SwaggerApiResponse } from '@src/common/swagger/swagger-response';

export function ApiReadManyLectureMyReview() {
  return applyDecorators(
    ApiOperation({
      summary: '작성한 리뷰 조회',
    }),
    ApiBearerAuth(),
    ApiOkResponse(
      SwaggerApiResponse.success('작성한 리뷰 조회완료', {
        statusCode: 200,
        data: {
          review: [
            {
              id: 34,
              lectureId: 59,
              userId: 56,
              reservationId: 26,
              stars: 5,
              description: '34번 리뷰입니다',
              createdAt: '2023-11-07T01:45:02.005Z',
              updatedAt: '2023-11-07T02:04:16.215Z',
              deletedAt: null,
              lecture: {
                id: 59,
                lecturerId: 4,
                lectureTypeId: 1,
                lectureMethodId: 1,
                isGroup: true,
                startDate: '2023-11-24T23:38:40.000Z',
                endDate: '2024-11-24T23:38:27.000Z',
                title: '결제 테스트',
                introduction: '잘 운영할 예정',
                curriculum: '1주차 휴강',
                duration: 2,
                difficultyLevel: '상',
                minCapacity: 1,
                maxCapacity: 10,
                reservationDeadline: 2,
                reservationComment: '유의사항 변경하기!!~~??',
                price: 40000,
                noShowDeposit: 30000,
                reviewCount: 0,
                stars: 0,
                isActive: true,
                locationDescription: '버스타고 한번에 갈 수 있어욤',
                createdAt: '2023-11-24T10:36:30.399Z',
                updatedAt: '2023-12-07T13:41:06.138Z',
                deletedAt: null,
              },
              reservation: {
                lectureSchedule: {
                  startDateTime: '2023-10-03T11:00:00.000Z',
                },
              },
              likedLectureReview: [],
              _count: {
                likedLectureReview: 0,
              },
            },
            {
              id: 33,
              lectureId: 59,
              userId: 56,
              reservationId: 27,
              stars: 5,
              description: '33번 리뷰입니다',
              createdAt: '2023-11-07T01:45:02.004Z',
              updatedAt: '2023-11-07T02:04:16.215Z',
              deletedAt: null,
              lecture: {
                id: 59,
                lecturerId: 4,
                lectureTypeId: 1,
                lectureMethodId: 1,
                isGroup: true,
                startDate: '2023-11-24T23:38:40.000Z',
                endDate: '2024-11-24T23:38:27.000Z',
                title: '결제 테스트',
                introduction: '잘 운영할 예정',
                curriculum: '1주차 휴강',
                duration: 2,
                difficultyLevel: '상',
                minCapacity: 1,
                maxCapacity: 10,
                reservationDeadline: 2,
                reservationComment: '유의사항 변경하기!!~~??',
                price: 40000,
                noShowDeposit: 30000,
                reviewCount: 0,
                stars: 0,
                isActive: true,
                locationDescription: '버스타고 한번에 갈 수 있어욤',
                createdAt: '2023-11-24T10:36:30.399Z',
                updatedAt: '2023-12-07T13:41:06.138Z',
                deletedAt: null,
              },
              reservation: {
                lectureSchedule: {
                  startDateTime: '2023-10-07T11:00:00.000Z',
                },
              },
              likedLectureReview: [],
              _count: {
                likedLectureReview: 0,
              },
            },
            {
              id: 32,
              lectureId: 59,
              userId: 56,
              reservationId: 25,
              stars: 2,
              description: '32번 리뷰입니다',
              createdAt: '2023-11-07T01:45:02.003Z',
              updatedAt: '2023-11-07T02:04:16.215Z',
              deletedAt: null,
              lecture: {
                id: 59,
                lecturerId: 4,
                lectureTypeId: 1,
                lectureMethodId: 1,
                isGroup: true,
                startDate: '2023-11-24T23:38:40.000Z',
                endDate: '2024-11-24T23:38:27.000Z',
                title: '결제 테스트',
                introduction: '잘 운영할 예정',
                curriculum: '1주차 휴강',
                duration: 2,
                difficultyLevel: '상',
                minCapacity: 1,
                maxCapacity: 10,
                reservationDeadline: 2,
                reservationComment: '유의사항 변경하기!!~~??',
                price: 40000,
                noShowDeposit: 30000,
                reviewCount: 0,
                stars: 0,
                isActive: true,
                locationDescription: '버스타고 한번에 갈 수 있어욤',
                createdAt: '2023-11-24T10:36:30.399Z',
                updatedAt: '2023-12-07T13:41:06.138Z',
                deletedAt: null,
              },
              reservation: {
                lectureSchedule: {
                  startDateTime: '2023-10-07T11:00:00.000Z',
                },
              },
              likedLectureReview: [],
              _count: {
                likedLectureReview: 0,
              },
            },
            {
              id: 31,
              lectureId: 59,
              userId: 56,
              reservationId: 24,
              stars: 3,
              description: '31번 리뷰입니다',
              createdAt: '2023-11-07T01:45:02.002Z',
              updatedAt: '2023-11-07T02:04:16.215Z',
              deletedAt: null,
              lecture: {
                id: 59,
                lecturerId: 4,
                lectureTypeId: 1,
                lectureMethodId: 1,
                isGroup: true,
                startDate: '2023-11-24T23:38:40.000Z',
                endDate: '2024-11-24T23:38:27.000Z',
                title: '결제 테스트',
                introduction: '잘 운영할 예정',
                curriculum: '1주차 휴강',
                duration: 2,
                difficultyLevel: '상',
                minCapacity: 1,
                maxCapacity: 10,
                reservationDeadline: 2,
                reservationComment: '유의사항 변경하기!!~~??',
                price: 40000,
                noShowDeposit: 30000,
                reviewCount: 0,
                stars: 0,
                isActive: true,
                locationDescription: '버스타고 한번에 갈 수 있어욤',
                createdAt: '2023-11-24T10:36:30.399Z',
                updatedAt: '2023-12-07T13:41:06.138Z',
                deletedAt: null,
              },
              reservation: {
                lectureSchedule: {
                  startDateTime: '2023-10-03T11:00:00.000Z',
                },
              },
              likedLectureReview: [],
              _count: {
                likedLectureReview: 0,
              },
            },
            {
              id: 30,
              lectureId: 59,
              userId: 56,
              reservationId: 23,
              stars: 4,
              description: '30번 리뷰입니다',
              createdAt: '2023-11-07T01:45:02.001Z',
              updatedAt: '2023-11-07T02:04:16.215Z',
              deletedAt: null,
              lecture: {
                id: 59,
                lecturerId: 4,
                lectureTypeId: 1,
                lectureMethodId: 1,
                isGroup: true,
                startDate: '2023-11-24T23:38:40.000Z',
                endDate: '2024-11-24T23:38:27.000Z',
                title: '결제 테스트',
                introduction: '잘 운영할 예정',
                curriculum: '1주차 휴강',
                duration: 2,
                difficultyLevel: '상',
                minCapacity: 1,
                maxCapacity: 10,
                reservationDeadline: 2,
                reservationComment: '유의사항 변경하기!!~~??',
                price: 40000,
                noShowDeposit: 30000,
                reviewCount: 0,
                stars: 0,
                isActive: true,
                locationDescription: '버스타고 한번에 갈 수 있어욤',
                createdAt: '2023-11-24T10:36:30.399Z',
                updatedAt: '2023-12-07T13:41:06.138Z',
                deletedAt: null,
              },
              reservation: {
                lectureSchedule: {
                  startDateTime: '2023-10-07T11:00:00.000Z',
                },
              },
              likedLectureReview: [
                {
                  id: 22,
                  lectureReviewId: 30,
                  userId: 56,
                },
              ],
              _count: {
                likedLectureReview: 2,
              },
            },
            {
              id: 29,
              lectureId: 59,
              userId: 56,
              reservationId: 22,
              stars: 5,
              description: '29번 리뷰입니다',
              createdAt: '2023-11-07T01:45:02.000Z',
              updatedAt: '2023-11-07T02:04:16.215Z',
              deletedAt: null,
              lecture: {
                id: 59,
                lecturerId: 4,
                lectureTypeId: 1,
                lectureMethodId: 1,
                isGroup: true,
                startDate: '2023-11-24T23:38:40.000Z',
                endDate: '2024-11-24T23:38:27.000Z',
                title: '결제 테스트',
                introduction: '잘 운영할 예정',
                curriculum: '1주차 휴강',
                duration: 2,
                difficultyLevel: '상',
                minCapacity: 1,
                maxCapacity: 10,
                reservationDeadline: 2,
                reservationComment: '유의사항 변경하기!!~~??',
                price: 40000,
                noShowDeposit: 30000,
                reviewCount: 0,
                stars: 0,
                isActive: true,
                locationDescription: '버스타고 한번에 갈 수 있어욤',
                createdAt: '2023-11-24T10:36:30.399Z',
                updatedAt: '2023-12-07T13:41:06.138Z',
                deletedAt: null,
              },
              reservation: {
                lectureSchedule: {
                  startDateTime: '2023-10-03T11:00:00.000Z',
                },
              },
              likedLectureReview: [
                {
                  id: 20,
                  lectureReviewId: 29,
                  userId: 56,
                },
              ],
              _count: {
                likedLectureReview: 6,
              },
            },
          ],
        },
      }),
    ),
  );
}
