export enum ReportTypes {
  FALSE_INFORMATION = 'FALSE_INFORMATION',
  COPYRIGHT_INFRINGEMENT = 'COPYRIGHT_INFRINGEMENT',
  INAPPROPRIATE_PHOTO = 'INAPPROPRIATE_PHOTO',
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  OTHER = 'OTHER',
}

export enum ReportFilterOptions {
  ALL = 'ALL',
  USER = 'USER',
  REVIEW = 'REVIEW',
}
