name: Connection-CICD

on:
  pull_request:
    branches: ['develop']
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Backend-Server
        run: npm ci

      - name: Compile Backend-Server
        run: npm run build
